spin_manifest_version = 2

[application]
name = "conmod-demo"
version = "0.1.0"
description = "An example content moderation application"

[variables]
api_token = { required = true }

[[trigger.http]]
route = "/api"
component = "api"

[component.api]
source = "target/wasm32-wasip1/release/conmod_api.wasm"
allowed_outbound_hosts = ["*://*:*"]
dependencies_inherit_configuration = true
[component.api.build]
command = "make build"

[component.api.variables]

token = "{{ api_token }}"

[component.api.dependencies]
"component:content-moderator/moderator" = { path = "target/wasm32-wasip1/release/content_moderator.wasm" }

[[trigger.http]]
route = "/..."
component = "static-fileserver"

[component.static-fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
