[package]
name = "conmod-api"
description = "An example API that uses the content moderation component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"
wit-bindgen = "0.16.0"